// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkflowsRequest) Reset() {
	*x = ScheduleWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkflowsRequest) ProtoMessage() {}

func (x *ScheduleWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ScheduleWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleWorkflowsRequest) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type ScheduleWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleWorkflowsResponse) Reset() {
	*x = ScheduleWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkflowsResponse) ProtoMessage() {}

func (x *ScheduleWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ScheduleWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type UnscheduleWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowIds   []string               `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnscheduleWorkflowsRequest) Reset() {
	*x = UnscheduleWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnscheduleWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnscheduleWorkflowsRequest) ProtoMessage() {}

func (x *UnscheduleWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnscheduleWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*UnscheduleWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *UnscheduleWorkflowsRequest) GetWorkflowIds() []string {
	if x != nil {
		return x.WorkflowIds
	}
	return nil
}

type UnscheduleWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnscheduleWorkflowsResponse) Reset() {
	*x = UnscheduleWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnscheduleWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnscheduleWorkflowsResponse) ProtoMessage() {}

func (x *UnscheduleWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnscheduleWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*UnscheduleWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

type PauseWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowIds   []string               `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseWorkflowsRequest) Reset() {
	*x = PauseWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseWorkflowsRequest) ProtoMessage() {}

func (x *PauseWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*PauseWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *PauseWorkflowsRequest) GetWorkflowIds() []string {
	if x != nil {
		return x.WorkflowIds
	}
	return nil
}

type PauseWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseWorkflowsResponse) Reset() {
	*x = PauseWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseWorkflowsResponse) ProtoMessage() {}

func (x *PauseWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*PauseWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

type ResumeWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowIds   []string               `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeWorkflowsRequest) Reset() {
	*x = ResumeWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeWorkflowsRequest) ProtoMessage() {}

func (x *ResumeWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ResumeWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeWorkflowsRequest) GetWorkflowIds() []string {
	if x != nil {
		return x.WorkflowIds
	}
	return nil
}

type ResumeWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeWorkflowsResponse) Reset() {
	*x = ResumeWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeWorkflowsResponse) ProtoMessage() {}

func (x *ResumeWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ResumeWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

type ModifyWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyWorkflowsRequest) Reset() {
	*x = ModifyWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyWorkflowsRequest) ProtoMessage() {}

func (x *ModifyWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ModifyWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyWorkflowsRequest) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type ModifyWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyWorkflowsResponse) Reset() {
	*x = ModifyWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyWorkflowsResponse) ProtoMessage() {}

func (x *ModifyWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ModifyWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

type ForceRunWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowIds   []string               `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceRunWorkflowsRequest) Reset() {
	*x = ForceRunWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceRunWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceRunWorkflowsRequest) ProtoMessage() {}

func (x *ForceRunWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceRunWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ForceRunWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *ForceRunWorkflowsRequest) GetWorkflowIds() []string {
	if x != nil {
		return x.WorkflowIds
	}
	return nil
}

type ForceRunWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceRunWorkflowsResponse) Reset() {
	*x = ForceRunWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceRunWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceRunWorkflowsResponse) ProtoMessage() {}

func (x *ForceRunWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceRunWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ForceRunWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

type GetWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowsIds  []string               `protobuf:"bytes,1,rep,name=workflows_ids,json=workflowsIds,proto3" json:"workflows_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowsRequest) Reset() {
	*x = GetWorkflowsRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowsRequest) ProtoMessage() {}

func (x *GetWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *GetWorkflowsRequest) GetWorkflowsIds() []string {
	if x != nil {
		return x.WorkflowsIds
	}
	return nil
}

type GetWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowsResponse) Reset() {
	*x = GetWorkflowsResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowsResponse) ProtoMessage() {}

func (x *GetWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Schedules     []*WorkflowSchedule    `protobuf:"bytes,4,rep,name=schedules,proto3" json:"schedules,omitempty"`
	LogDriver     string                 `protobuf:"bytes,5,opt,name=log_driver,json=logDriver,proto3" json:"log_driver,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,7,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetSchedules() []*WorkflowSchedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *Workflow) GetLogDriver() string {
	if x != nil {
		return x.LogDriver
	}
	return ""
}

func (x *Workflow) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Workflow) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Workflow) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type WorkflowSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextRun       int64                  `protobuf:"varint,1,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	RepeatEvery   int64                  `protobuf:"varint,2,opt,name=repeat_every,json=repeatEvery,proto3" json:"repeat_every,omitempty"`
	Times         int64                  `protobuf:"varint,3,opt,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSchedule) Reset() {
	*x = WorkflowSchedule{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSchedule) ProtoMessage() {}

func (x *WorkflowSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSchedule.ProtoReflect.Descriptor instead.
func (*WorkflowSchedule) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *WorkflowSchedule) GetNextRun() int64 {
	if x != nil {
		return x.NextRun
	}
	return 0
}

func (x *WorkflowSchedule) GetRepeatEvery() int64 {
	if x != nil {
		return x.RepeatEvery
	}
	return 0
}

func (x *WorkflowSchedule) GetTimes() int64 {
	if x != nil {
		return x.Times
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Executor      string                 `protobuf:"bytes,4,opt,name=executor,proto3" json:"executor,omitempty"`
	Commands      []string               `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`
	Dependencies  []*JobDependency       `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Retries       int64                  `protobuf:"varint,7,opt,name=retries,proto3" json:"retries,omitempty"`
	RetryBackoff  int64                  `protobuf:"varint,8,opt,name=retry_backoff,json=retryBackoff,proto3" json:"retry_backoff,omitempty"`
	Timeout       int64                  `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Job) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Job) GetDependencies() []*JobDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Job) GetRetries() int64 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Job) GetRetryBackoff() int64 {
	if x != nil {
		return x.RetryBackoff
	}
	return 0
}

func (x *Job) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type JobDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DependencyId  int64                  `protobuf:"varint,1,opt,name=dependency_id,json=dependencyId,proto3" json:"dependency_id,omitempty"`
	When          string                 `protobuf:"bytes,2,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDependency) Reset() {
	*x = JobDependency{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDependency) ProtoMessage() {}

func (x *JobDependency) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDependency.ProtoReflect.Descriptor instead.
func (*JobDependency) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *JobDependency) GetDependencyId() int64 {
	if x != nil {
		return x.DependencyId
	}
	return 0
}

func (x *JobDependency) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\"C\n" +
	"\x18ScheduleWorkflowsRequest\x12'\n" +
	"\tworkflows\x18\x01 \x03(\v2\t.WorkflowR\tworkflows\"\x1b\n" +
	"\x19ScheduleWorkflowsResponse\"?\n" +
	"\x1aUnscheduleWorkflowsRequest\x12!\n" +
	"\fworkflow_ids\x18\x01 \x03(\tR\vworkflowIds\"\x1d\n" +
	"\x1bUnscheduleWorkflowsResponse\":\n" +
	"\x15PauseWorkflowsRequest\x12!\n" +
	"\fworkflow_ids\x18\x01 \x03(\tR\vworkflowIds\"\x18\n" +
	"\x16PauseWorkflowsResponse\";\n" +
	"\x16ResumeWorkflowsRequest\x12!\n" +
	"\fworkflow_ids\x18\x01 \x03(\tR\vworkflowIds\"\x19\n" +
	"\x17ResumeWorkflowsResponse\"A\n" +
	"\x16ModifyWorkflowsRequest\x12'\n" +
	"\tworkflows\x18\x01 \x03(\v2\t.WorkflowR\tworkflows\"\x19\n" +
	"\x17ModifyWorkflowsResponse\"=\n" +
	"\x18ForceRunWorkflowsRequest\x12!\n" +
	"\fworkflow_ids\x18\x01 \x03(\tR\vworkflowIds\"\x1b\n" +
	"\x19ForceRunWorkflowsResponse\":\n" +
	"\x13GetWorkflowsRequest\x12#\n" +
	"\rworkflows_ids\x18\x01 \x03(\tR\fworkflowsIds\"?\n" +
	"\x14GetWorkflowsResponse\x12'\n" +
	"\tworkflows\x18\x01 \x03(\v2\t.WorkflowR\tworkflows\"\xf3\x01\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\tschedules\x18\x04 \x03(\v2\x11.WorkflowScheduleR\tschedules\x12\x1d\n" +
	"\n" +
	"log_driver\x18\x05 \x01(\tR\tlogDriver\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\x04jobs\x18\a \x03(\v2\x04.JobR\x04jobs\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"f\n" +
	"\x10WorkflowSchedule\x12\x19\n" +
	"\bnext_run\x18\x01 \x01(\x03R\anextRun\x12!\n" +
	"\frepeat_every\x18\x02 \x01(\x03R\vrepeatEvery\x12\x14\n" +
	"\x05times\x18\x03 \x01(\x03R\x05times\"\x8f\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bexecutor\x18\x04 \x01(\tR\bexecutor\x12\x1a\n" +
	"\bcommands\x18\x05 \x03(\tR\bcommands\x122\n" +
	"\fdependencies\x18\x06 \x03(\v2\x0e.JobDependencyR\fdependencies\x12\x18\n" +
	"\aretries\x18\a \x01(\x03R\aretries\x12#\n" +
	"\rretry_backoff\x18\b \x01(\x03R\fretryBackoff\x12\x18\n" +
	"\atimeout\x18\t \x01(\x03R\atimeout\"H\n" +
	"\rJobDependency\x12#\n" +
	"\rdependency_id\x18\x01 \x01(\x03R\fdependencyId\x12\x12\n" +
	"\x04when\x18\x02 \x01(\tR\x04when2\xfa\x03\n" +
	"\x04Flux\x12J\n" +
	"\x11ScheduleWorkflows\x12\x19.ScheduleWorkflowsRequest\x1a\x1a.ScheduleWorkflowsResponse\x12P\n" +
	"\x13UnscheduleWorkflows\x12\x1b.UnscheduleWorkflowsRequest\x1a\x1c.UnscheduleWorkflowsResponse\x12@\n" +
	"\rPauseWorkflow\x12\x16.PauseWorkflowsRequest\x1a\x17.PauseWorkflowsResponse\x12C\n" +
	"\x0eResumeWorkflow\x12\x17.ResumeWorkflowsRequest\x1a\x18.ResumeWorkflowsResponse\x12D\n" +
	"\x0fModifyWorkflows\x12\x17.ModifyWorkflowsRequest\x1a\x18.ModifyWorkflowsResponse\x12J\n" +
	"\x11ForceRunWorkflows\x12\x19.ForceRunWorkflowsRequest\x1a\x1a.ForceRunWorkflowsResponse\x12;\n" +
	"\fGetWorkflows\x12\x14.GetWorkflowsRequest\x1a\x15.GetWorkflowsResponseB\"Z github.com/lamentoeldi/flux/grpcb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_goTypes = []any{
	(*ScheduleWorkflowsRequest)(nil),    // 0: ScheduleWorkflowsRequest
	(*ScheduleWorkflowsResponse)(nil),   // 1: ScheduleWorkflowsResponse
	(*UnscheduleWorkflowsRequest)(nil),  // 2: UnscheduleWorkflowsRequest
	(*UnscheduleWorkflowsResponse)(nil), // 3: UnscheduleWorkflowsResponse
	(*PauseWorkflowsRequest)(nil),       // 4: PauseWorkflowsRequest
	(*PauseWorkflowsResponse)(nil),      // 5: PauseWorkflowsResponse
	(*ResumeWorkflowsRequest)(nil),      // 6: ResumeWorkflowsRequest
	(*ResumeWorkflowsResponse)(nil),     // 7: ResumeWorkflowsResponse
	(*ModifyWorkflowsRequest)(nil),      // 8: ModifyWorkflowsRequest
	(*ModifyWorkflowsResponse)(nil),     // 9: ModifyWorkflowsResponse
	(*ForceRunWorkflowsRequest)(nil),    // 10: ForceRunWorkflowsRequest
	(*ForceRunWorkflowsResponse)(nil),   // 11: ForceRunWorkflowsResponse
	(*GetWorkflowsRequest)(nil),         // 12: GetWorkflowsRequest
	(*GetWorkflowsResponse)(nil),        // 13: GetWorkflowsResponse
	(*Workflow)(nil),                    // 14: Workflow
	(*WorkflowSchedule)(nil),            // 15: WorkflowSchedule
	(*Job)(nil),                         // 16: Job
	(*JobDependency)(nil),               // 17: JobDependency
}
var file_api_proto_depIdxs = []int32{
	14, // 0: ScheduleWorkflowsRequest.workflows:type_name -> Workflow
	14, // 1: ModifyWorkflowsRequest.workflows:type_name -> Workflow
	14, // 2: GetWorkflowsResponse.workflows:type_name -> Workflow
	15, // 3: Workflow.schedules:type_name -> WorkflowSchedule
	16, // 4: Workflow.jobs:type_name -> Job
	17, // 5: Job.dependencies:type_name -> JobDependency
	0,  // 6: Flux.ScheduleWorkflows:input_type -> ScheduleWorkflowsRequest
	2,  // 7: Flux.UnscheduleWorkflows:input_type -> UnscheduleWorkflowsRequest
	4,  // 8: Flux.PauseWorkflow:input_type -> PauseWorkflowsRequest
	6,  // 9: Flux.ResumeWorkflow:input_type -> ResumeWorkflowsRequest
	8,  // 10: Flux.ModifyWorkflows:input_type -> ModifyWorkflowsRequest
	10, // 11: Flux.ForceRunWorkflows:input_type -> ForceRunWorkflowsRequest
	12, // 12: Flux.GetWorkflows:input_type -> GetWorkflowsRequest
	1,  // 13: Flux.ScheduleWorkflows:output_type -> ScheduleWorkflowsResponse
	3,  // 14: Flux.UnscheduleWorkflows:output_type -> UnscheduleWorkflowsResponse
	5,  // 15: Flux.PauseWorkflow:output_type -> PauseWorkflowsResponse
	7,  // 16: Flux.ResumeWorkflow:output_type -> ResumeWorkflowsResponse
	9,  // 17: Flux.ModifyWorkflows:output_type -> ModifyWorkflowsResponse
	11, // 18: Flux.ForceRunWorkflows:output_type -> ForceRunWorkflowsResponse
	13, // 19: Flux.GetWorkflows:output_type -> GetWorkflowsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
