// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flux_ScheduleWorkflows_FullMethodName   = "/Flux/ScheduleWorkflows"
	Flux_UnscheduleWorkflows_FullMethodName = "/Flux/UnscheduleWorkflows"
	Flux_PauseWorkflow_FullMethodName       = "/Flux/PauseWorkflow"
	Flux_ResumeWorkflow_FullMethodName      = "/Flux/ResumeWorkflow"
	Flux_ModifyWorkflows_FullMethodName     = "/Flux/ModifyWorkflows"
	Flux_ForceRunWorkflows_FullMethodName   = "/Flux/ForceRunWorkflows"
	Flux_GetWorkflows_FullMethodName        = "/Flux/GetWorkflows"
)

// FluxClient is the client API for Flux service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FluxClient interface {
	ScheduleWorkflows(ctx context.Context, in *ScheduleWorkflowsRequest, opts ...grpc.CallOption) (*ScheduleWorkflowsResponse, error)
	UnscheduleWorkflows(ctx context.Context, in *UnscheduleWorkflowsRequest, opts ...grpc.CallOption) (*UnscheduleWorkflowsResponse, error)
	PauseWorkflow(ctx context.Context, in *PauseWorkflowsRequest, opts ...grpc.CallOption) (*PauseWorkflowsResponse, error)
	ResumeWorkflow(ctx context.Context, in *ResumeWorkflowsRequest, opts ...grpc.CallOption) (*ResumeWorkflowsResponse, error)
	ModifyWorkflows(ctx context.Context, in *ModifyWorkflowsRequest, opts ...grpc.CallOption) (*ModifyWorkflowsResponse, error)
	ForceRunWorkflows(ctx context.Context, in *ForceRunWorkflowsRequest, opts ...grpc.CallOption) (*ForceRunWorkflowsResponse, error)
	GetWorkflows(ctx context.Context, in *GetWorkflowsRequest, opts ...grpc.CallOption) (*GetWorkflowsResponse, error)
}

type fluxClient struct {
	cc grpc.ClientConnInterface
}

func NewFluxClient(cc grpc.ClientConnInterface) FluxClient {
	return &fluxClient{cc}
}

func (c *fluxClient) ScheduleWorkflows(ctx context.Context, in *ScheduleWorkflowsRequest, opts ...grpc.CallOption) (*ScheduleWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_ScheduleWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxClient) UnscheduleWorkflows(ctx context.Context, in *UnscheduleWorkflowsRequest, opts ...grpc.CallOption) (*UnscheduleWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnscheduleWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_UnscheduleWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxClient) PauseWorkflow(ctx context.Context, in *PauseWorkflowsRequest, opts ...grpc.CallOption) (*PauseWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_PauseWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxClient) ResumeWorkflow(ctx context.Context, in *ResumeWorkflowsRequest, opts ...grpc.CallOption) (*ResumeWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_ResumeWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxClient) ModifyWorkflows(ctx context.Context, in *ModifyWorkflowsRequest, opts ...grpc.CallOption) (*ModifyWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_ModifyWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxClient) ForceRunWorkflows(ctx context.Context, in *ForceRunWorkflowsRequest, opts ...grpc.CallOption) (*ForceRunWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceRunWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_ForceRunWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fluxClient) GetWorkflows(ctx context.Context, in *GetWorkflowsRequest, opts ...grpc.CallOption) (*GetWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowsResponse)
	err := c.cc.Invoke(ctx, Flux_GetWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FluxServer is the server API for Flux service.
// All implementations must embed UnimplementedFluxServer
// for forward compatibility.
type FluxServer interface {
	ScheduleWorkflows(context.Context, *ScheduleWorkflowsRequest) (*ScheduleWorkflowsResponse, error)
	UnscheduleWorkflows(context.Context, *UnscheduleWorkflowsRequest) (*UnscheduleWorkflowsResponse, error)
	PauseWorkflow(context.Context, *PauseWorkflowsRequest) (*PauseWorkflowsResponse, error)
	ResumeWorkflow(context.Context, *ResumeWorkflowsRequest) (*ResumeWorkflowsResponse, error)
	ModifyWorkflows(context.Context, *ModifyWorkflowsRequest) (*ModifyWorkflowsResponse, error)
	ForceRunWorkflows(context.Context, *ForceRunWorkflowsRequest) (*ForceRunWorkflowsResponse, error)
	GetWorkflows(context.Context, *GetWorkflowsRequest) (*GetWorkflowsResponse, error)
	mustEmbedUnimplementedFluxServer()
}

// UnimplementedFluxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFluxServer struct{}

func (UnimplementedFluxServer) ScheduleWorkflows(context.Context, *ScheduleWorkflowsRequest) (*ScheduleWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleWorkflows not implemented")
}
func (UnimplementedFluxServer) UnscheduleWorkflows(context.Context, *UnscheduleWorkflowsRequest) (*UnscheduleWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnscheduleWorkflows not implemented")
}
func (UnimplementedFluxServer) PauseWorkflow(context.Context, *PauseWorkflowsRequest) (*PauseWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseWorkflow not implemented")
}
func (UnimplementedFluxServer) ResumeWorkflow(context.Context, *ResumeWorkflowsRequest) (*ResumeWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeWorkflow not implemented")
}
func (UnimplementedFluxServer) ModifyWorkflows(context.Context, *ModifyWorkflowsRequest) (*ModifyWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyWorkflows not implemented")
}
func (UnimplementedFluxServer) ForceRunWorkflows(context.Context, *ForceRunWorkflowsRequest) (*ForceRunWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceRunWorkflows not implemented")
}
func (UnimplementedFluxServer) GetWorkflows(context.Context, *GetWorkflowsRequest) (*GetWorkflowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflows not implemented")
}
func (UnimplementedFluxServer) mustEmbedUnimplementedFluxServer() {}
func (UnimplementedFluxServer) testEmbeddedByValue()              {}

// UnsafeFluxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FluxServer will
// result in compilation errors.
type UnsafeFluxServer interface {
	mustEmbedUnimplementedFluxServer()
}

func RegisterFluxServer(s grpc.ServiceRegistrar, srv FluxServer) {
	// If the following call pancis, it indicates UnimplementedFluxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flux_ServiceDesc, srv)
}

func _Flux_ScheduleWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).ScheduleWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_ScheduleWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).ScheduleWorkflows(ctx, req.(*ScheduleWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flux_UnscheduleWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnscheduleWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).UnscheduleWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_UnscheduleWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).UnscheduleWorkflows(ctx, req.(*UnscheduleWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flux_PauseWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).PauseWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_PauseWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).PauseWorkflow(ctx, req.(*PauseWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flux_ResumeWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).ResumeWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_ResumeWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).ResumeWorkflow(ctx, req.(*ResumeWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flux_ModifyWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).ModifyWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_ModifyWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).ModifyWorkflows(ctx, req.(*ModifyWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flux_ForceRunWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRunWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).ForceRunWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_ForceRunWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).ForceRunWorkflows(ctx, req.(*ForceRunWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flux_GetWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FluxServer).GetWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flux_GetWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FluxServer).GetWorkflows(ctx, req.(*GetWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Flux_ServiceDesc is the grpc.ServiceDesc for Flux service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flux_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Flux",
	HandlerType: (*FluxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleWorkflows",
			Handler:    _Flux_ScheduleWorkflows_Handler,
		},
		{
			MethodName: "UnscheduleWorkflows",
			Handler:    _Flux_UnscheduleWorkflows_Handler,
		},
		{
			MethodName: "PauseWorkflow",
			Handler:    _Flux_PauseWorkflow_Handler,
		},
		{
			MethodName: "ResumeWorkflow",
			Handler:    _Flux_ResumeWorkflow_Handler,
		},
		{
			MethodName: "ModifyWorkflows",
			Handler:    _Flux_ModifyWorkflows_Handler,
		},
		{
			MethodName: "ForceRunWorkflows",
			Handler:    _Flux_ForceRunWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflows",
			Handler:    _Flux_GetWorkflows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
